config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :users

  root 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :notes

	validates :name, presence: true
	validates :password, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
require "json"

class NotesController < ApplicationController
  include NotesHelper
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.includes(:user).order('notes.created_at DESC').all
    @note = Note.new
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    # Get the note contents
    content = params[:note][:content]

    # Check if we have a logged in user
    user = JSON.load(cookies[:current_user])

    # Cookie the note so that the user controller can create the note
    # before redirecting back to the notes page
    cookies[:content] = content

    # If not, then have user sign up
    if user.nil?
      redirect_to new_user_path, content: content
      return
    end

    # Create the note otherwise
    @note = create_note(content, user['id'])
    respond_to do |format|
      if @note
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
      #  format.json { render :index, status: :created }
      else
        format.html { render :index }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    user = JSON.load(cookies[:current_user])
    respond_to do |format|
      if @note.update({ :content => params[:note][:content], :user_id => user['id'] })
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
      #  format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
require "json"

class UsersController < ApplicationController
  include NotesHelper
  include UsersHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @newuser = User.new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    puts "params = " + params.to_s
    if (params[:commit] == 'Sign In')
      signin
      return
    end

    # Create new user
    if (not user_exists(params[:user][:email]))
      @newuser = User.new(user_params)
      respond_to do |format|
        if @newuser.save
          # Cookie the newly created user
          cookies[:current_user] =  { 'id' => @newuser.id, 'name' => @newuser.name }.to_json
          notice_msg = 'User was successfully created. '
          puts "cookies[:content] = " + cookies[:content].to_s
          if (cookies[:content])
            create_note(cookies[:content], @newuser.id)
            notice_msg = notice_msg + 'Note was successfully created.'
          end
          format.html { redirect_to notes_path, notice: notice_msg }
        else
          format.html { render :new }
          format.json { render json: @newuser.errors, status: :unprocessable_entity }
        end
      end
    else
      @newuser = User.new  
      respond_to do |format|
        format.html { render :new, notice: 'User with specified email already exists.' }
      end
    end
  end

  def signin
    puts 'in signin method'
    signedin_user = signin_user(params[:user][:email], params[:user][:password])
    respond_to do |format|
      if signedin_user
        @user = signedin_user
        puts signedin_user.id

        # Cookie the newly created user
        cookies[:current_user] =  { 'id' => @user.id, 'name' => @user.name }.to_json
        notice_msg = 'Login successful. '
        if (cookies[:content])
          create_note(cookies[:content], @user.id)
          notice_msg = notice_msg + 'Note was successfully created.'
        end
        format.html { redirect_to notes_path, notice: notice_msg }
      else
        @user = User.new
        format.html { render :new, notice: 'Email/password combination not found' }
        #format.json { render json: 'Email/password combination not found', status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
	def create_note(content, user_id)
	    note = Note.new({ :content => content, :user_id => user_id })
	    if note.save
	    	return note
	    end
	    return nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def get_user(user_email)
		User.find_by email: user_email
	end

	def signin_user(user_email, user_password)
		user = get_user(user_email)
		if user && user.password == user_password
			return user
		end
		return nil
	end

	def user_exists(user_email)
		get_user(user_email) ? true : false
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, 'Enter note' %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div id="greeting">
  <% current_user = JSON.load(cookies[:current_user]) %>
  <% if not current_user.nil? %> 
       <p>Hello, <%= current_user['name'] %></p>      
  <% else %>
       <p><%= link_to 'Sign In', new_user_path %></p>
  <% end %>
</div>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th>Updated On</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.content %></td>
        <td><%= note.user.nil? ? 'nil' : note.user.name %></td>
        <td></td>
        <td><%= note.updated_at %></td>
        <td></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- Display new note partial view -->
<%= render :partial => 'form' %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/users/_form.html.erb
<%= form_for(@newuser) do |f| %>
  <% if @newuser && @newuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newuser.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @newuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_signin.html.erb
<%= form_for(@user, :html=> {:id => 'signin_user'}) do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign In'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign In To Your Account</h1>

<%= render 'signin' %>
<p>OR</p>
<h1>Sign Up For An Account</h1>
<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', notes_path %>